[[Tokens]]
TxType = "swapin"
PairID = "eth"
SwapServer = "http://127.0.0.1:11556/rpc"
TokenAddress = "native"
DepositAddress = "0xaF0A46d3700E23a98F38079cE217742c92aa66aC"

[[Tokens]]
TxType = "swapin"
PairID = "usdt"
SwapServer = "http://127.0.0.1:22556/rpc"
TokenAddress = "0x61b8c4d6d28d5f7edadbea5456db3b4f7f836b64"
DepositAddress = "0xbF0A46d3700E23a98F38079cE217742c92Bb66bC"

[[Tokens]]
TxType = "swapout"
PairID = "bsc"
SwapServer = "http://127.0.0.1:33556/rpc"
TokenAddress = "0x71b8c4d7d28d5f7edadbea5457db3b4f7f837b74"

[[Tokens]]
TxType = "swapout2"
PairID = "btc"
SwapServer = "http://127.0.0.1:44556/rpc"
TokenAddress = "0x81b8c4d8d28d5f8edadbea5458db3b4f8f838b84"
